### PR TITLE
Fix RegistrationForm to work with custom models

### PR DESCRIPTION
**Pull request by robertobarreda**

### CODE REVIEW

**Comment by ubernostrum** [comment]
Could you explain what this has to do with custom models? It looks like instead it's adding support for the new password validation system.

**Comment by ubernostrum** [comment]
Also, if that's what this is doing, it's actually unnecessary -- django-registration subclasses Django's default `UserCreationForm` and so inherits the `clean_password2` logic automatically.

**Comment by robertobarreda** [comment]
The problem I found in dj <=1.9 is that the following line crashes with my custom model that doesn't have an **username** field:

https://github.com/django/django/blob/1.9.4/django/contrib/auth/forms.py#L89

**Comment by ubernostrum** [comment]
You'll want to read [the documentation for custom user models in django-registration](https://github.com/ubernostrum/django-registration/blob/master/docs/custom-user.rst), then. Needing to write your own form subclass is an expected part of integrating a custom user model, and trying to support every possible model configuration without custom code is not something django-registration will do.

**Pull request closed without merging**
