### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by kosmos342**

### CODE REVIEW

**Comment by kosmos342** [comment]
I created simple project for test. https://github.com/kosmos342/drtest
Also I used your patch for registration's test https://gist.github.com/ubernostrum/f1abc7a6c13787210e8d021a0c8f77c1

Please note: that problem with non ascii username affect only python 2

**Comment by ubernostrum** [comment]
I'm going to close this because it's not due to django-registration; django.contrib.auth rejects non-ASCII usernames on Python 2, and django-registration is not going to override that by default.

**Comment by kosmos342** [comment]
Django provide customization of User model. django-registration application can use customized User model. So I don't understand why you closed this PR

**Comment by ubernostrum** [comment]
The reason why it doesn't work is *because* the default Django `UserCreationForm` is applying the validation of the default Django `User` model. If you correctly supply your own custom user model with its own creation form, you will not have this problem. Thus, there is nothing for django-registration to do here.

**Pull request closed without merging**
