### PR TITLE
Use newer class-based views when available

### LINKED ISSUE #94: Leaking of password reset token through the reset url
I think it is possible to leak the password reset token since it is left in the url. 

In Django 1.11 the token is stripped during a redirect ([docs](https://docs.djangoproject.com/en/1.11/releases/1.11/#django-contrib-auth), [code](https://github.com/django/django/blob/1.11.2/django/contrib/auth/views.py#L461)) to prevent the token from being taken in the referrer header from 3rd party apps on the page. I haven't dug too deeply into the source for this project but at a first glance it seems that the vulnerability exists since the older auth view functions are used and not the class based views.

If this is the case would be happy to help fix similar to [django-registration-redux](https://github.com/macropin/django-registration/pull/268), or at the very least alert you to the issue. Let me know if you guys need any help!

### PR DESCRIPTION
**Pull request by joshblum**
Fixes #94 if users are on newer versions of Django

### CODE REVIEW

**Comment by ubernostrum** [comment]
I don't understand what this is trying to accomplish; on newer Django, the old names are aliases of the new class-based views (i.e., `django.contrib.auth.views.login` is an alias of `LoginView.as_view()` in Django 1.11).

**Comment by joshblum** [comment]
They are not just aliases, if you read the release notes these views are updated while the function based views are not. In particular the `PasswordResetConfirmView` has a fix:

>  To avoid the possibility of leaking a password reset token via the HTTP Referer header (for example, if the reset page includes a reference to CSS or JavaScript hosted on another domain), the `PasswordResetConfirmView` (but not the deprecated` password_reset_confirm() `function-based view) stores the token in a session and redirects to itself to present the password change form to the user without the token in the URL.


https://docs.djangoproject.com/en/1.11/releases/1.11/#django-contrib-auth

**Comment by joshblum** [comment]
@ubernostrum I'm getting an `InvocationError` when running the coverage report, do you know a potential fix? Location I am able to run the testing commands individually.

```
ERROR: InvocationError: '/home/travis/build/ubernostrum/django-registration/.tox/py36-django111/bin/coverage report -m'
```

**Comment by ubernostrum** [comment]
The `InvocationError` means that one of the test commands has a non-zero exit status.

In this case, it's the coverage report, which is telling you that you didn't get to 100% coverage. If you look above that at the coverage output, you'll see line 63 of `registration/auth_urls.py` is the line missing coverage.

**Comment by joshblum** [comment]
@ubernostrum the lines that are missed  (63 or 31) is where the code branches based on the django version so coverage will never be 100%. How would you like me to fix? Would a `#noqa` be appropiate or can the coverage be allowed less than 100% on a file?

**Comment by ubernostrum** [comment]
Probably going to involve assigning views to local names based on which ones are defined.

**Comment by joshblum** [comment]
@ubernostrum can you provide a concrete example of what you mean? The PR is editable by maintainers so if it's easier to get this merged you can directly edit it.

**Comment by ubernostrum** [comment]
See 1a0068df703a646f2ccefcdce89502162d15efe2 for one option.

**Comment by joshblum** [comment]
Cool thanks for helping.

**Pull request closed without merging**
