### PR TITLE
Pass user to email activation template

### PR DESCRIPTION
**Pull request by xrmx**
It's quite handy being able to reference the user by name in the activation email.

### CODE REVIEW

**Comment by ubernostrum** [comment]
The idea here is fine, but could you make the same change in the HMAC workflow, for consistency?

**Comment by xrmx** [comment]
@ubernostrum sure, is it ok to change RegistrationView.get_email_context to take a user instead of activation_key or backward compatibility should be kept?

**Comment by ubernostrum** [comment]
I don't see a reason why the user needs to be passed to `get_email_context()` since it can be added in afterward -- that method is mostly so people can add things when overriding, not to remove things that the base implementation already includes. I'm half tempted to remove the activation key as an argument, too, and just force it into the context in `send_activation_email()`. But let me think about it a bit.

**Comment by xrmx** [comment]
Had any chance to review it? thanks

**Comment by ubernostrum** [comment]
Sorry for the delay, was a busy time as I moved across the country. This is on my to-do list to review and act on within the next week.

**Comment by ubernostrum** [comment]
OK, this looks right to me, and I think it's about the cleanest way available to do it across the different ways the backends work. I'll try to do one more pass over it tomorrow and then merge so it can be part of the 2.1 release.

**Comment by xrmx** [comment]
Thanks!

**Pull request merged**
