### PR TITLE
Fix #106 - Enable Auth-CBV Success Redirects

### LINKED ISSUE #106: Password reset yields 404 "Page not found" error
Following the [quickstart documentation](http://django-registration.readthedocs.io/en/latest/quickstart.html), I set up a [project](https://bitbucket.org/j/django-registration-testproject/src) that yields a 404 "Page not found" error when attempting a password reset. The URL it is trying to load is: http://localhost:8000/accounts/password/reset/auth_password_reset_done

## Steps to reproduce
Create a Python 3.6.2 virtualenv and a Django 1.11.4 project, then install django-registration (current master, 89812bcde9d1e4875d5ce7dc737b4b176da98884):
```
virtualenv -p python3 testproject
pip install django git+https://github.com/ubernostrum/django-registration.git#egg=django-registration
django-admin startproject testproject
cd testproject/
```

I then made what I believe are the needed modifications to get started, which can be seen here: https://bitbucket.org/j/django-registration-testproject/src

Migrate and create user:
```
python manage.py migrate
python manage.py createsuperuser
python manage.py runserver
```

Visit in browser: http://localhost:8000/accounts/password/reset/

Enter email address from `createsuperuser` step. Tap "Reset Password" button.

## Expected result

URL route http://localhost:8000/accounts/password/reset/done/ would be loaded.

## Observed result

Erroneous URL is loaded: http://localhost:8000/accounts/password/reset/auth_password_reset_done

<details>
<summary>(Tap here to see traceback)</summary>

```
Page not found (404)
Request Method: | GET
http://localhost:8000/accounts/password/reset/auth_password_reset_done

Using the URLconf defined in testproject.urls, Django tried these URL patterns, in this order:
^accounts/ ^activate/complete/$ [name='registration_activation_complete']
^accounts/ ^activate/(?P<activation_key>[-:\w]+)/$ [name='registration_activate']
^accounts/ ^register/$ [name='registration_register']
^accounts/ ^register/complete/$ [name='registration_complete']
^accounts/ ^register/closed/$ [name='registration_disallowed']
^accounts/ ^login/$ [name='auth_login']
^accounts/ ^logout/$ [name='auth_logout']
^accounts/ ^password/change/$ [name='auth_password_change']
^accounts/ ^password/change/done/$ [name='auth_password_change_done']
^accounts/ ^password/reset/$ [name='auth_password_reset']
^accounts/ ^password/reset/complete/$ [name='auth_password_reset_complete']
^accounts/ ^password/reset/done/$ [name='auth_password_reset_done']
^accounts/ ^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$ [name='auth_password_reset_confirm']
^admin/
The current path, accounts/password/reset/auth_password_reset_done, didn't match any of these.
```

</details>

## Additional notes

I'm happy to provide any additional information needed to help track down this problem. If, on the other hand, this is a [PEBKAC](https://en.wikipedia.org/wiki/User_error#Acronyms_and_other_names) issue, I'd appreciate any suggestions as to how to avoid this situation. Thank you!

### PR DESCRIPTION
**Pull request by jambonrose**
This PR supersedes #111, and will occur in two parts.

1. I will open this PR with a commit that intentionally fails the test suite.

2. I will then push a commit that fixes the tests. This commit is actually a cherry-picked and isorted version of @securedirective's fix from #111.

The goal of these two actions is to ensure that the tests I have written properly target the error that I am fixing.

Please let me know if you'd like any modifications or whatnot.

### CODE REVIEW

**Comment by alessioferri20** [comment]
This fix will ever be implemented? because I'm facing the same problem!

**Comment by jambonrose** [comment]
I'll update this PR to account for changes in `master` ASAP.

**Comment by briceparent** [comment]
Quickfix : Until it's done, and as I couldn't wait (the website is live), I've added hard-coded urls inside my main urls.py. It works, but as it's duplicating things, it might break future updates. So use with caution ! 

To do so, just copy the routes for 'auth_password_change', 'auth_password_reset' and 'auth_password_reset_confirm' in your urls.py before the inclusion of 'registration.backends.hmac.urls', and modify the success_url parameter by calling reverse_lazy on it (ex : `success_url='auth_password_reset_complete'` becomes `success_url=reverse_lazy('auth_password_reset_complete')`). 

You might have to add the following 2 imports to your urls.py:
* from django.contrib.auth import views as auth_views
* from django.urls import reverse_lazy

To be removed once the problem has been fixed in django-registration.

**Comment by jambonrose** [comment]
For other's discovering this PR: to expand on @briceparent's workaround, the following code may be of interest (use at your own peril!). It results in each view in the HMAC workflow existing only once on the site, avoiding the duplication @briceparent refers to.

https://github.com/jambonsw/django-improved-user/blob/f9f51f2b69ada5295e702b151fcceea4721cdd16/example_integration_project/user_integration/urls.py

**Comment by rsd** [comment]
works as a charm:
`pip install -e git+https://github.com/jambonrose/django-registration.git@fix_issue_106_add_reverse_lazy#egg=django-registration`

**Comment by ubernostrum** [comment]
All PRs against 2.x are currently on hold until 3.x is out the door. Then a final 2.x bugfix will go out.

**Comment by ubernostrum** [comment]
This is merged and in a release. This is the absolute final for-real end of the line of django-registration 2.x.

**Comment by bbelderbos** [comment]
Awesome this got in, thanks

**Pull request merged**
