### PR TITLE
For upstream/django-dry

### PR DESCRIPTION
**Pull request by c0d3z3r0**

### CODE REVIEW

**Comment by c0d3z3r0** [comment]
I have no clue how to fix that coverage error...

**Comment by c0d3z3r0** [comment]
any comments on this?

**Comment by ubernostrum** [comment]
Need to do some thinking on this one, but it's on my radar.

**Comment by c0d3z3r0** [comment]
If you want to see it in action just look at https://github.com/c0d3z3r0/ctf-backend/blob/stable/ctfbackend/backend/forms.py

**Comment by ubernostrum** [comment]
My main concern here is that it's slightly backwards-incompatible, since Django's `UserCreationForm` puts the password-mismatch error on the second password field, but django-registration's form has it as a form-level error not tied to any field. Need to decide if it's worth the breakage.

**Comment by ubernostrum** [comment]
This change actually is a bit more in-depth than your patch, especially given that it naturally leads the various functions/methods to pass around the form instance and use `form.save()` instead of passing around the `cleaned_data`. I've implemented the full change, plus documentation on the backwards-incompatible changes, in 59a7b80b21ac3bf44003d5805ef44ecfa8efd714.

**Comment by c0d3z3r0** [comment]
Great, your change even makes it simplier to use django-multiform for user profile creation :+1:

**Pull request closed without merging**
