### PR TITLE
Fix cleanup of actual active users

### PR DESCRIPTION
**Pull request by nikolaik**
This keeps the behaviour as it were before 626d876

After bumping to v2.1 suddenly most of your active users could be gone :boom:

### CODE REVIEW

**Comment by nikolaik** [comment]
Or should we change the behaviour to allways delete the profile but only delete inactive users?

**Comment by strindhaug** [comment]
I assume the cleanup command always was supposed to delete the expired profiles and only delete the user if not active. Because I don't see the benefit of storing hundreds of profiles saying "ALREADY_ACTIVATED" in the database.

**Comment by strindhaug** [comment]
#46

**Comment by ubernostrum** [comment]
For the moment it is meant to keep the profiles around; they have some uses. So I went with a different approach in e9c9e2c9d3bf6e0f02fe7e2b24b55360207be09f and fixed the `expired()` query itself to do the right thing.

**Comment by strindhaug** [comment]
What other uses does the profile have? After registration it's just a OneToOneField relation between a user and the string "ALREADY_ACTIVATED", as far as I can see...

It looks like it's back to old behaviour, which is better, but while investigating this issue I've realized that the old behaviour is a lot more destructive than "cleanup registration" implies. I've created a new issue for this: https://github.com/ubernostrum/django-registration/issues/48

**Pull request closed without merging**
