### PR TITLE
Fix error with non ascii username field in python 2

### PR DESCRIPTION
**Pull request by kosmos342**

### CODE REVIEW

**Comment by ubernostrum** [comment]
If this affects the model backend, it probably affects at least the HMAC one, too; have you tested that?

**Comment by kosmos342** [comment]
I didn't test HMAC

**Comment by ubernostrum** [comment]
I've just run [this test](https://gist.github.com/ubernostrum/f1abc7a6c13787210e8d021a0c8f77c1) (which you can try out in your own local copy of django-registration by applying the linked patch), and all three registration workflows passed with it.

Strongly suspect you have your database configured with a charset that just doesn't allow Unicode, or some other configuration issue is going on, and closing since I can't reproduce any failure in django-registration.

**Comment by kosmos342** [comment]
Did you use python2?

**Comment by kosmos342** [comment]
With your test's path I get 0 failures in python3 and 6 failures in python2 on master branch. but with my pull request it got 6 failures too:)

**Pull request closed without merging**
