### PR TITLE
Fix #113 - make pw reset email consistent

### LINKED ISSUE #113: Password-Reset Email-Template Changed in v2.3 for Django 1.11+
The behavior of the password reset feature changes when either (1) upgrading `django-registration` from 2.2 to 2.3 on a Django 1.11+ site or else (2) upgrading from Django 1.x to 1.11 with `django-registration` v2.3 installed. The password reset email template used by `django-registration` changes depending on whether function views or class-based views are used by [`auth_url_module`](https://github.com/ubernostrum/django-registration/blob/cd8430d5074bfe6f4c7931a3f37ea67511ea9be2/registration/auth_urls.py#L23).

In `django-registration` 2.2 and with v2.3 [function auth views](https://github.com/ubernostrum/django-registration/blob/cd8430d5074bfe6f4c7931a3f37ea67511ea9be2/registration/auth_urls_functions.py), the password reset view email template is [overridden to `registration/password_reset_email.txt`](https://github.com/ubernostrum/django-registration/blob/cd8430d5074bfe6f4c7931a3f37ea67511ea9be2/registration/auth_urls_functions.py#L42). However, the 2.3 [class auth views](https://github.com/ubernostrum/django-registration/blob/cd8430d5074bfe6f4c7931a3f37ea67511ea9be2/registration/auth_urls_classes.py) use Django's default email template, which is [`registration/password_reset_email.html`](https://github.com/django/django/blob/stable/1.11.x/django/contrib/auth/views.py#L426) (note the difference in file extension).

What's more, if `'django.contrib.admin'` appears in the INSTALLED_APPS list before a local app that provides a local `registration/password_reset_email.html`, the the site will use [Django's template](https://github.com/django/django/blob/stable/1.11.x/django/contrib/admin/templates/registration/password_reset_email.html). That can be a problem, as the template attempts to reverse to a URL named `'password_reset_confirm'`, which does not exist on the site if the developer is relying on `django-registration` URLs (the view is instead `auth_password_reset_confirm`).

Given current behavior, developers either have the choice of (1) writing out their own URL configuration (optimal, but more work), (2) changing the order of their INSTALLED_APPS (undesirable), (3) adding a duplicate set of Django auth views (terrible).

If `registration.auth_urls` were intended as a long-term feature, I would advocate sticking with Django's defaults and simply noting the backwards-incompatible change in a change-log. However, given that the intent is to remove `registration.auth_urls` in v3.0 (as noted in #78), I suspect that a patch to make the class-based views use the same template as function views and previous releases may be the best solution.

### PR DESCRIPTION
**Pull request by jambonrose**
I am opening this PR with a new test, but no changes to the code. The goal is to make reviewing the code as simple as possible. I will let the tests run on TravisCI to demonstrate failing tests, and then push a new commit to demonstrate the fix with a second test run.

### CODE REVIEW

**Comment by jambonrose** [comment]
Unless you'd like me to make any changes, I believe this is ready to go.

Please note that I have intentionally not changed the `success_url` argument, despite #106 .

**Comment by jambonrose** [comment]
I realized this morning that I did a terrible job naming the test and file I created. 

Given some of the discussion on PR #111, I think this test suite/file could serve as the integration tests for the Django Auth URLs (as that PR seeks to fix a bug in the same domain). This will allow you to simply delete this file when moving to v3.

I got the name of the suite/class right, but the name of the file and the name of the test are rather unhelpful. I'll push one last commit to try and fix that.

**Comment by ubernostrum** [comment]
@jambonrose Your last comment indicated another commit was coming, but I don't see it -- should I still be expecting something further before I review this fully?

**Comment by jambonrose** [comment]
@ubernostrum : The commit to change the name of the test is b68bc26, which is the commit listed before my comment. I suspect I may have written the comment, forgotten to submit it, and submitted it just as I pushed the commit. Apologies for the confusion. This is ready for full review.

For clarity:
- 158e201 demonstrates the failing test
- dd2785e fixes the issue
- b68bc26 renames the test for clarity (because I did a terrible job in the first commit)

FWIW, TravisCI jobs [#363.2](https://travis-ci.org/ubernostrum/django-registration/jobs/281959192) and [#363.3](https://travis-ci.org/ubernostrum/django-registration/jobs/281959193) best demonstrate the new failing test and inconsistent behavior:
```
 py35-django18: commands succeeded
 py35-django110: commands succeeded
ERROR: py35-django111: commands failed
```

I hope this makes review easier.

**Comment by ubernostrum** [comment]
OK, I should have time this weekend to look into this, and I definitely want to try to get this stuff into a 2.3.1 or maybe a 2.4 before I start removing deprecated stuff for 3.0.

**Pull request merged**
